import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const catalogPath = path.resolve(here, '../../packages/core/resources/errors.json');
const outputPath = path.resolve(here, '../src/content/docs/reference/errors.md');
const check = process.argv.includes('--check');

const catalog = JSON.parse(await readFile(catalogPath, 'utf8'));
if (!Array.isArray(catalog.errors)) throw new Error('Error catalog must contain an errors array.');

const seen = new Set();
for (const entry of catalog.errors) {
  if (!/^ATOMS-E\d{3}$/.test(entry.code)) throw new Error(`Invalid error code: ${entry.code}`);
  if (seen.has(entry.code)) throw new Error(`Duplicate error code: ${entry.code}`);
  seen.add(entry.code);
}

const escape = (value) => String(value).replaceAll('\\', '\\\\').replaceAll('`', '\\`');
const sections = catalog.errors.map((entry) => `
<a id="${entry.code.toLowerCase()}"></a>

## ${entry.code}: ${entry.title}

| | |
|---|---|
| Severity | \`${escape(entry.severity)}\` |
| Phase | \`${escape(entry.phase)}\` |

**Message**

${entry.message}

**Fix**

${entry.fix}
`).join('\n');

const generated = `---
title: Error catalog
description: Every stable Atoms error code, generated from the atoms/core catalog.
editUrl: false
---

<!-- Generated by docs-site/scripts/generate-errors.mjs. Do not edit by hand. -->

Find the code from your exception or CLI output below. Each entry describes the failure and suggests what to check. This page is generated from \`packages/core/resources/errors.json\`.
${sections}`;

if (check) {
  const current = await readFile(outputPath, 'utf8').catch(() => '');
  if (current !== generated) {
    throw new Error('Generated error reference is stale. Run npm run generate:errors in docs-site/.');
  }
} else {
  await writeFile(outputPath, generated);
}

console.log(`${check ? 'Verified' : 'Generated'} ${catalog.errors.length} error entries.`);
